/** Currencies for Book Me pay rate */
export const PAY_CURRENCIES = [
  { value: 'USD', label: 'USD - US Dollar - $', symbol: '$' },
  { value: 'AFN', label: 'AFN - Afghan Afghani - ؋', symbol: '؋' },
  { value: 'ALL', label: 'ALL - Albanian Lek - L', symbol: 'L' },
  { value: 'DZD', label: 'DZD - Algerian Dinar - د.ج', symbol: 'د.ج' },
  { value: 'AOA', label: 'AOA - Angolan Kwanza - Kz', symbol: 'Kz' },
  { value: 'ARS', label: 'ARS - Argentine Peso - $', symbol: '$' },
  { value: 'AMD', label: 'AMD - Armenian Dram - ֏', symbol: '֏' },
  { value: 'AWG', label: 'AWG - Aruban Florin - ƒ', symbol: 'ƒ' },
  { value: 'AUD', label: 'AUD - Australian Dollar - A$', symbol: 'A$' },
  { value: 'AZN', label: 'AZN - Azerbaijani Manat - ₼', symbol: '₼' },
  { value: 'BSD', label: 'BSD - Bahamian Dollar - $', symbol: '$' },
  { value: 'BHD', label: 'BHD - Bahraini Dinar - .د.ب', symbol: '.د.ب' },
  { value: 'BDT', label: 'BDT - Bangladeshi Taka - ৳', symbol: '৳' },
  { value: 'BBD', label: 'BBD - Barbadian Dollar - $', symbol: '$' },
  { value: 'BYN', label: 'BYN - Belarusian Ruble - Br', symbol: 'Br' },
  { value: 'BZD', label: 'BZD - Belize Dollar - BZ$', symbol: 'BZ$' },
  { value: 'BMD', label: 'BMD - Bermudan Dollar - $', symbol: '$' },
  { value: 'BTN', label: 'BTN - Bhutanese Ngultrum - Nu.', symbol: 'Nu.' },
  { value: 'BTC', label: 'BTC - Bitcoin - ₿', symbol: '₿' },
  { value: 'BOB', label: 'BOB - Bolivian Boliviano - Bs.', symbol: 'Bs.' },
  { value: 'BAM', label: 'BAM - Bosnia-Herzegovina Convertible Mark - KM', symbol: 'KM' },
  { value: 'BWP', label: 'BWP - Botswanan Pula - P', symbol: 'P' },
  { value: 'BRL', label: 'BRL - Brazilian Real - R$', symbol: 'R$' },
  { value: 'GBP', label: 'GBP - British Pound Sterling - £', symbol: '£' },
  { value: 'BND', label: 'BND - Brunei Dollar - $', symbol: '$' },
  { value: 'BGN', label: 'BGN - Bulgarian Lev - лв', symbol: 'лв' },
  { value: 'BIF', label: 'BIF - Burundian Franc - FBu', symbol: 'FBu' },
  { value: 'KHR', label: 'KHR - Cambodian Riel - ៛', symbol: '៛' },
  { value: 'CAD', label: 'CAD - Canadian Dollar - C$', symbol: 'C$' },
  { value: 'CVE', label: 'CVE - Cape Verdean Escudo - $', symbol: '$' },
  { value: 'KYD', label: 'KYD - Cayman Islands Dollar - $', symbol: '$' },
  { value: 'XOF', label: 'XOF - CFA Franc BCEAO - CFA', symbol: 'CFA' },
  { value: 'XAF', label: 'XAF - CFA Franc BEAC - FCFA', symbol: 'FCFA' },
  { value: 'XPF', label: 'XPF - CFP Franc - ₣', symbol: '₣' },
  { value: 'CLP', label: 'CLP - Chilean Peso - $', symbol: '$' },
  { value: 'CNY', label: 'CNY - Chinese Yuan - ¥', symbol: '¥' },
  { value: 'COP', label: 'COP - Colombian Peso - $', symbol: '$' },
  { value: 'KMF', label: 'KMF - Comorian Franc - CF', symbol: 'CF' },
  { value: 'CDF', label: 'CDF - Congolese Franc - FC', symbol: 'FC' },
  { value: 'CRC', label: 'CRC - Costa Rican Colón - ₡', symbol: '₡' },
  { value: 'HRK', label: 'HRK - Croatian Kuna - kn', symbol: 'kn' },
  { value: 'CUP', label: 'CUP - Cuban Peso - $', symbol: '$' },
  { value: 'CZK', label: 'CZK - Czech Koruna - Kč', symbol: 'Kč' },
  { value: 'DKK', label: 'DKK - Danish Krone - kr', symbol: 'kr' },
  { value: 'DJF', label: 'DJF - Djiboutian Franc - Fdj', symbol: 'Fdj' },
  { value: 'DOP', label: 'DOP - Dominican Peso - RD$', symbol: 'RD$' },
  { value: 'XCD', label: 'XCD - East Caribbean Dollar - EC$', symbol: 'EC$' },
  { value: 'EGP', label: 'EGP - Egyptian Pound - £', symbol: '£' },
  { value: 'ERN', label: 'ERN - Eritrean Nakfa - Nfk', symbol: 'Nfk' },
  { value: 'ETB', label: 'ETB - Ethiopian Birr - Br', symbol: 'Br' },
  { value: 'EUR', label: 'EUR - Euro - €', symbol: '€' },
  { value: 'FKP', label: 'FKP - Falkland Islands Pound - £', symbol: '£' },
  { value: 'FJD', label: 'FJD - Fijian Dollar - FJ$', symbol: 'FJ$' },
  { value: 'GMD', label: 'GMD - Gambian Dalasi - D', symbol: 'D' },
  { value: 'GEL', label: 'GEL - Georgian Lari - ₾', symbol: '₾' },
  { value: 'GHS', label: 'GHS - Ghanaian Cedi - ₵', symbol: '₵' },
  { value: 'GIP', label: 'GIP - Gibraltar Pound - £', symbol: '£' },
  { value: 'GTQ', label: 'GTQ - Guatemalan Quetzal - Q', symbol: 'Q' },
  { value: 'GGP', label: 'GGP - Guernsey pound - £', symbol: '£' },
  { value: 'GNF', label: 'GNF - Guinean Franc - FG', symbol: 'FG' },
  { value: 'GYD', label: 'GYD - Guyanaese Dollar - $', symbol: '$' },
  { value: 'HTG', label: 'HTG - Haitian Gourde - G', symbol: 'G' },
  { value: 'HNL', label: 'HNL - Honduran Lempira - L', symbol: 'L' },
  { value: 'HKD', label: 'HKD - Hong Kong Dollar - HK$', symbol: 'HK$' },
  { value: 'HUF', label: 'HUF - Hungarian Forint - Ft', symbol: 'Ft' },
  { value: 'ISK', label: 'ISK - Icelandic Króna - kr', symbol: 'kr' },
  { value: 'INR', label: 'INR - Indian Rupee - ₹', symbol: '₹' },
  { value: 'IDR', label: 'IDR - Indonesian Rupiah - Rp', symbol: 'Rp' },
  { value: 'IRR', label: 'IRR - Iranian Rial - ﷼', symbol: '﷼' },
  { value: 'IQD', label: 'IQD - Iraqi Dinar - ع.د', symbol: 'ع.د' },
  { value: 'ILS', label: 'ILS - Israeli New Sheqel - ₪', symbol: '₪' },
  { value: 'JMD', label: 'JMD - Jamaican Dollar - J$', symbol: 'J$' },
  { value: 'JPY', label: 'JPY - Japanese Yen - ¥', symbol: '¥' },
  { value: 'JEP', label: 'JEP - Jersey pound - £', symbol: '£' },
  { value: 'JOD', label: 'JOD - Jordanian Dinar - د.ا', symbol: 'د.ا' },
  { value: 'KZT', label: 'KZT - Kazakhstani Tenge - ₸', symbol: '₸' },
  { value: 'KES', label: 'KES - Kenyan Shilling - KSh', symbol: 'KSh' },
  { value: 'KWD', label: 'KWD - Kuwaiti Dinar - د.ك', symbol: 'د.ك' },
  { value: 'KGS', label: 'KGS - Kyrgystani Som - с', symbol: 'с' },
  { value: 'LAK', label: 'LAK - Laotian Kip - ₭', symbol: '₭' },
  { value: 'LBP', label: 'LBP - Lebanese Pound - ل.ل', symbol: 'ل.ل' },
  { value: 'LSL', label: 'LSL - Lesotho Loti - L', symbol: 'L' },
  { value: 'LRD', label: 'LRD - Liberian Dollar - $', symbol: '$' },
  { value: 'LYD', label: 'LYD - Libyan Dinar - ل.د', symbol: 'ل.د' },
  { value: 'MOP', label: 'MOP - Macanese Pataca - MOP$', symbol: 'MOP$' },
  { value: 'MKD', label: 'MKD - Macedonian Denar - ден', symbol: 'ден' },
  { value: 'MGA', label: 'MGA - Malagasy Ariary - Ar', symbol: 'Ar' },
  { value: 'MWK', label: 'MWK - Malawian Kwacha - MK', symbol: 'MK' },
  { value: 'MYR', label: 'MYR - Malaysian Ringgit - RM', symbol: 'RM' },
  { value: 'MVR', label: 'MVR - Maldivian Rufiyaa - Rf', symbol: 'Rf' },
  { value: 'MRU', label: 'MRU - Mauritanian Ouguiya - UM', symbol: 'UM' },
  { value: 'MUR', label: 'MUR - Mauritian Rupee - ₨', symbol: '₨' },
  { value: 'MXN', label: 'MXN - Mexican Peso - $', symbol: '$' },
  { value: 'MDL', label: 'MDL - Moldovan Leu - L', symbol: 'L' },
  { value: 'MNT', label: 'MNT - Mongolian Tugrik - ₮', symbol: '₮' },
  { value: 'MAD', label: 'MAD - Moroccan Dirham - د.م.', symbol: 'د.م.' },
  { value: 'MZN', label: 'MZN - Mozambican Metical - MT', symbol: 'MT' },
  { value: 'MMK', label: 'MMK - Myanmar Kyat - Ks', symbol: 'Ks' },
  { value: 'NAD', label: 'NAD - Namibian Dollar - $', symbol: '$' },
  { value: 'NPR', label: 'NPR - Nepalese Rupee - ₨', symbol: '₨' },
  { value: 'ANG', label: 'ANG - Netherlands Antillean Guilder - ƒ', symbol: 'ƒ' },
  { value: 'TWD', label: 'TWD - New Taiwan Dollar - NT$', symbol: 'NT$' },
  { value: 'NZD', label: 'NZD - New Zealand Dollar - $', symbol: '$' },
  { value: 'NIO', label: 'NIO - Nicaraguan Córdoba - C$', symbol: 'C$' },
  { value: 'NGN', label: 'NGN - Nigerian Naira - ₦', symbol: '₦' },
  { value: 'KPW', label: 'KPW - North Korean Won - ₩', symbol: '₩' },
  { value: 'NOK', label: 'NOK - Norwegian Krone - kr', symbol: 'kr' },
  { value: 'OMR', label: 'OMR - Omani Rial - ر.ع.', symbol: 'ر.ع.' },
  { value: 'PKR', label: 'PKR - Pakistani Rupee - ₨', symbol: '₨' },
  { value: 'PAB', label: 'PAB - Panamanian Balboa - B/.', symbol: 'B/.' },
  { value: 'PGK', label: 'PGK - Papua New Guinean Kina - K', symbol: 'K' },
  { value: 'PYG', label: 'PYG - Paraguayan Guarani - ₲', symbol: '₲' },
  { value: 'PEN', label: 'PEN - Peruvian Sol - S/', symbol: 'S/' },
  { value: 'PHP', label: 'PHP - Philippine Peso - ₱', symbol: '₱' },
  { value: 'PLN', label: 'PLN - Polish Zloty - zł', symbol: 'zł' },
  { value: 'QAR', label: 'QAR - Qatari Rial - ر.ق', symbol: 'ر.ق' },
  { value: 'RON', label: 'RON - Romanian Leu - lei', symbol: 'lei' },
  { value: 'RUB', label: 'RUB - Russian Ruble - ₽', symbol: '₽' },
  { value: 'RWF', label: 'RWF - Rwandan Franc - FRw', symbol: 'FRw' },
  { value: 'SAR', label: 'SAR - Saudi Riyal - ر.س', symbol: 'ر.س' },
  { value: 'SGD', label: 'SGD - Singapore Dollar - $', symbol: '$' },
  { value: 'ZAR', label: 'ZAR - South African Rand - R', symbol: 'R' },
  { value: 'KRW', label: 'KRW - South Korean Won - ₩', symbol: '₩' },
  { value: 'SDG', label: 'SDG - Sudanese Pound - ج.س.', symbol: 'ج.س.' },
  { value: 'SRD', label: 'SRD - Surinamese Dollar - $', symbol: '$' },
  { value: 'SZL', label: 'SZL - Swazi Lilangeni - L', symbol: 'L' },
  { value: 'SEK', label: 'SEK - Swedish Krona - kr', symbol: 'kr' },
  { value: 'CHF', label: 'CHF - Swiss Franc - CHF', symbol: 'CHF' },
  { value: 'STN', label: 'STN - São Tomé and Príncipe Dobra - Db', symbol: 'Db' },
  { value: 'THB', label: 'THB - Thai Baht - ฿', symbol: '฿' },
  { value: 'TTD', label: 'TTD - Trinidad and Tobago dollar - TT$', symbol: 'TT$' },
  { value: 'TRY', label: 'TRY - Turkey Lira - TRY', symbol: 'TRY' },
  { value: 'UAH', label: 'UAH - Ukrainian Hryvnia - ₴', symbol: '₴' },
  { value: 'AED', label: 'AED - United Arab Emirates Dirham - د.إ', symbol: 'د.إ' },
  { value: 'VES', label: 'VES - Venezuelan Bolívar - Bs.S', symbol: 'Bs.S' },
  { value: 'ZMW', label: 'ZMW - Zambian Kwacha - ZK', symbol: 'ZK' },
];
