/** Language options for Personal Stats (multi-select) */
export const LANGUAGE_OPTIONS = [
  { id: "ab", name: "Abkhazian (Аҧсуа)" },
  { id: "af", name: "Afrikaans" },
  { id: "sq", name: "Albanian (Shqip)" },
  { id: "am", name: "Amharic (አማርኛ)" },
  { id: "ar", name: "Arabic (العربية)" },
  { id: "an", name: "Aragonese (Aragonés)" },
  { id: "hy", name: "Armenian (Հայերեն)" },
  { id: "as", name: "Assamese (অসমীয়া)" },
  { id: "ast", name: "Asturian (Asturianu)" },
  { id: "av", name: "Avaric (магӀарул мацӀ)" },
  { id: "ae", name: "Avestan (avesta)" },
  { id: "ay", name: "Aymara (Aymar aru)" },
  { id: "az", name: "Azerbaijani (Azərbaycan dili)" },
  { id: "bm", name: "Bambara (bamanankan)" },
  { id: "ba", name: "Bashkir (башҡорт теле)" },
  { id: "eu", name: "Basque (Euskara)" },
  { id: "be", name: "Belarusian (Беларуская)" },
  { id: "bn", name: "Bengali (বাংলা)" },
  { id: "bh", name: "Bihari (भोजपुरी)" },
  { id: "bi", name: "Bislama (Bislama)" },
  { id: "brx", name: "Bodo (बर')" },
  { id: "bs", name: "Bosnian (Bosanski)" },
  { id: "br", name: "Breton (Brezhoneg)" },
  { id: "bg", name: "Bulgarian (Български)" },
  { id: "my", name: "Burmese (ဗမာစာ)" },
  { id: "ca", name: "Catalan (Català)" },
  { id: "ckb", name: "Central Kurdish (کوردی)" },
  { id: "ch", name: "Chamorro (Chamoru)" },
  { id: "ce", name: "Chechen (Нохчийн мотт)" },
  { id: "ny", name: "Chichewa (chiCheŵa)" },
  { id: "zh", name: "Chinese (中文)" },
  { id: "zh-HK", name: "Chinese Hong Kong (中文 - 香港)" },
  { id: "zh-CN", name: "Chinese Simplified (中文简体)" },
  { id: "zh-TW", name: "Chinese Traditional (中文繁體)" },
  { id: "cv", name: "Chuvash (чӑваш чӗлхи)" },
  { id: "kw", name: "Cornish (Kernowek)" },
  { id: "co", name: "Corsican (Corsu)" },
  { id: "cr", name: "Cree (ᓀᐦᐃᔭᐍᐏᐣ)" },
  { id: "hr", name: "Croatian (Hrvatski)" },
  { id: "cs", name: "Czech (Čeština)" },
  { id: "da", name: "Danish (Dansk)" },
  { id: "dv", name: "Dhivehi (ދިވެހި)" },
  { id: "nl", name: "Dutch (Nederlands)" },
  { id: "dz", name: "Dzongkha (རྫོང་ཁ)" },
  { id: "en", name: "English" },
  { id: "en-AU", name: "English (Australia)" },
  { id: "en-CA", name: "English (Canada)" },
  { id: "en-IN", name: "English (India)" },
  { id: "en-NZ", name: "English (New Zealand)" },
  { id: "en-ZA", name: "English (South Africa)" },
  { id: "en-GB", name: "English (United Kingdom)" },
  { id: "en-US", name: "English (United States)" },
  { id: "eo", name: "Esperanto" },
  { id: "et", name: "Estonian (Eesti)" },
  { id: "ee", name: "Ewe (Eʋegbe)" },
  { id: "fo", name: "Faroese (Føroyskt)" },
  { id: "fj", name: "Fijian (vosa Vakaviti)" },
  { id: "fil", name: "Filipino (Wikang Filipino)" },
  { id: "fi", name: "Finnish (Suomi)" },
  { id: "fr", name: "French (Français)" },
  { id: "fr-CA", name: "French Canada (Français Canada)" },
  { id: "fr-FR", name: "French France (Français France)" },
  { id: "fr-CH", name: "French Switzerland (Français Suisse)" },
  { id: "ff", name: "Fula (Fulfulde)" },
  { id: "gl", name: "Galician (Galego)" },
  { id: "ka", name: "Georgian (ქართული)" },
  { id: "de", name: "German (Deutsch)" },
  { id: "de-AT", name: "German Austria (Deutsch Österreich)" },
  { id: "de-DE", name: "German Germany (Deutsch Deutschland)" },
  { id: "de-LI", name: "German Liechtenstein (Deutsch Liechtenstein)" },
  { id: "de-CH", name: "German Switzerland (Deutsch Schweiz)" },
  { id: "el", name: "Greek (Ελληνικά)" },
  { id: "gn", name: "Guarani (Avañe'ẽ)" },
  { id: "gu", name: "Gujarati (ગુજરાતી)" },
  { id: "ht", name: "Haitian (Creole)" },
  { id: "ha", name: "Hausa (هَوُسَ)" },
  { id: "haw", name: "Hawaiian (ʻŌlelo Hawaiʻi)" },
  { id: "he", name: "Hebrew (עברית)" },
  { id: "hz", name: "Herero (Otjiherero)" },
  { id: "hi", name: "Hindi (हिन्दी)" },
  { id: "ho", name: "Hiri Motu (Hiri Motu)" },
  { id: "hu", name: "Hungarian (Magyar)" },
  { id: "is", name: "Icelandic (Íslenska)" },
  { id: "io", name: "Ido (Ido)" },
  { id: "ig", name: "Igbo (Asụsụ Igbo)" },
  { id: "id", name: "Indonesian (Bahasa Indonesia)" },
  { id: "ia", name: "Interlingua (Interlingua)" },
  { id: "iu", name: "Inuktitut (ᐃᓄᒃᑎᑐᑦ)" },
  { id: "ik", name: "Inupiaq (Iñupiatun)" },
  { id: "ga", name: "Irish (Gaeilge)" },
  { id: "it", name: "Italian (Italiano)" },
  { id: "it-IT", name: "Italian Italy (Italiano Italia)" },
  { id: "it-CH", name: "Italian Switzerland (Italiano - Svizzera)" },
  { id: "ja", name: "Japanese (日本語)" },
  { id: "jv", name: "Javanese (ꦧꦱꦗꦮ)" },
  { id: "kl", name: "Kalaallisut (Kalaallisut)" },
  { id: "kn", name: "Kannada (ಕನ್ನಡ)" },
  { id: "ks", name: "Kashmiri (कॉशुर / كٲشُر‎)" },
  { id: "kk", name: "Kazakh (Қазақ тілі)" },
  { id: "km", name: "Khmer (ខ្មែរ)" },
  { id: "ki", name: "Kikuyu (Gĩkũyũ)" },
  { id: "rw", name: "Kinyarwanda (Ikinyarwanda)" },
  { id: "kv", name: "Komi (коми кыв)" },
  { id: "kg", name: "Kongo (Kikongo)" },
  { id: "ko", name: "Korean (한국어)" },
  { id: "ku", name: "Kurdish (Kurdî)" },
  { id: "kj", name: "Kwanyama (Kuanyama)" },
  { id: "ky", name: "Kyrgyz (Кыргызча)" },
  { id: "lo", name: "Lao (ລາວ)" },
  { id: "la", name: "Latin (Latina)" },
  { id: "lv", name: "Latvian (Latviešu)" },
  { id: "ln", name: "Lingala (Lingála)" },
  { id: "lt", name: "Lithuanian (Lietuvių)" },
  { id: "lg", name: "Luganda (Luganda)" },
  { id: "lb", name: "Luxembourgish (Lëtzebuergesch)" },
  { id: "mk", name: "Macedonian (Македонски)" },
  { id: "mai", name: "Maithili (मैथिली)" },
  { id: "ms", name: "Malay (Bahasa Melayu)" },
  { id: "ml", name: "Malayalam (മലയാളം)" },
  { id: "mt", name: "Maltese (Malti)" },
  { id: "mni", name: "Manipuri (ꯃꯅꯤꯄꯨꯔꯤ)" },
  { id: "gv", name: "Manx (Gaelg)" },
  { id: "mr", name: "Marathi (मराठी)" },
  { id: "mh", name: "Marshallese (Kajin M̧ajeļ)" },
  { id: "mn", name: "Mongolian (Монгол)" },
  { id: "na", name: "Nauru (Dorerin Naoero)" },
  { id: "nv", name: "Navajo (Diné bizaad)" },
  { id: "ng", name: "Ndonga (Owambo)" },
  { id: "ne", name: "Nepali (नेपाली)" },
  { id: "nd", name: "North Ndebele (isiNdebele)" },
  { id: "nr", name: "South Ndebele (isiNdebele)" },
  { id: "nso", name: "Northern Sotho (Sesotho sa Leboa)" },
  { id: "no", name: "Norwegian (Norsk)" },
  { id: "nb", name: "Norwegian Bokmål (Norsk bokmål)" },
  { id: "nn", name: "Norwegian Nynorsk (Nynorsk)" },
  { id: "ii", name: "Nuosu (ꆈꌠ꒿ Nuosuhxop)" },
  { id: "oc", name: "Occitan (occitan)" },
  { id: "or", name: "Oriya (ଓଡ଼ିଆ)" },
  { id: "om", name: "Oromo (Afaan Oromoo)" },
  { id: "os", name: "Ossetian (Ирон æвзаг)" },
  { id: "pi", name: "Pāli (पाऴि)" },
  { id: "ps", name: "Pashto (پښتو)" },
  { id: "fa", name: "Persian (فارسی)" },
  { id: "pl", name: "Polish (Polski)" },
  { id: "pt", name: "Portuguese (Português)" },
  { id: "pt-BR", name: "Portuguese Brazil (Português Brasil)" },
  { id: "pt-PT", name: "Portuguese Portugal (Português Portugal)" },
  { id: "pa", name: "Punjabi (ਪੰਜਾਬੀ)" },
  { id: "qu", name: "Quechua (Runa Simi)" },
  { id: "ro", name: "Romanian (Română)" },
  { id: "mo", name: "Romanian Moldova (Română Moldova)" },
  { id: "rm", name: "Romansh (Rumantsch)" },
  { id: "ru", name: "Russian (Русский)" },
  { id: "sm", name: "Samoan (Gagana Samoa)" },
  { id: "sg", name: "Sango (yângâ tî sängö)" },
  { id: "sa", name: "Sanskrit (संस्कृतम्)" },
  { id: "sat", name: "Santali (ᱥᱟᱱᱛᱟᱲᱤ)" },
  { id: "sc", name: "Sardinian (Sardu)" },
  { id: "gd", name: "Scottish Gaelic (Gàidhlig)" },
  { id: "sr", name: "Serbian (Српски)" },
  { id: "sh", name: "Serbo Croatian (Srpskohrvatski)" },
  { id: "sn", name: "Shona (ChiShona)" },
  { id: "sd", name: "Sindhi (سنڌي)" },
  { id: "si", name: "Sinhala (සිංහල)" },
  { id: "sk", name: "Slovak (Slovenčina)" },
  { id: "sl", name: "Slovenian (Slovenščina)" },
  { id: "so", name: "Somali (Soomaali)" },
  { id: "st", name: "Southern Sotho (Sesotho)" },
  { id: "es", name: "Spanish (Español)" },
  { id: "es-AR", name: "Spanish Argentina (Español Argentina)" },
  { id: "es-419", name: "Spanish Latin America (Español Latinoamérica)" },
  { id: "es-MX", name: "Spanish Mexico (Español México)" },
  { id: "es-ES", name: "Spanish Spain (Español España)" },
  { id: "es-US", name: "Spanish United States (Español Estados Unidos)" },
  { id: "su", name: "Sundanese (Basa Sunda)" },
  { id: "sw", name: "Swahili (Kiswahili)" },
  { id: "ss", name: "Swati (siSwati)" },
  { id: "sv", name: "Swedish (Svenska)" },
  { id: "ty", name: "Tahitian (Reo Tahiti)" },
  { id: "tg", name: "Tajik (Тоҷикӣ)" },
  { id: "tl", name: "Tagalog (Wikang Tagalog)" },
  { id: "ta", name: "Tamil (தமிழ்)" },
  { id: "tt", name: "Tatar (Татар)" },
  { id: "te", name: "Telugu (తెలుగు)" },
  { id: "th", name: "Thai (ไทย)" },
  { id: "bo", name: "Tibetan (བོད་ཡིག)" },
  { id: "ti", name: "Tigrinya (ትግርኛ)" },
  { id: "to", name: "Tongan (Lea fakatonga)" },
  { id: "ts", name: "Tsonga (Xitsonga)" },
  { id: "tn", name: "Tswana (Setswana)" },
  { id: "tr", name: "Turkish (Türkçe)" },
  { id: "tk", name: "Turkmen (Türkmençe)" },
  { id: "tw", name: "Twi (Twi)" },
  { id: "udm", name: "Udmurt (Удмурт кыл)" },
  { id: "uk", name: "Ukrainian (Українська)" },
  { id: "ur", name: "Urdu (اردو)" },
  { id: "ug", name: "Uyghur (ئۇيغۇرچە)" },
  { id: "uz", name: "Uzbek (O'zbek)" },
  { id: "ve", name: "Venda (Tshivenḓa)" },
  { id: "vo", name: "Volapük (Volapük)" },
  { id: "wa", name: "Walloon (Walon)" },
  { id: "cy", name: "Welsh (Cymraeg)" },
  { id: "fy", name: "Western Frisian (Frysk)" },
  { id: "wo", name: "Wolof (Wollof)" },
  { id: "xh", name: "Xhosa (isiXhosa)" },
  { id: "yi", name: "Yiddish (ייִדיש)" },
  { id: "yo", name: "Yoruba (Èdè Yorùbá)" },
  { id: "za", name: "Zhuang (Saɯ cueŋƅ)" },
  { id: "zu", name: "Zulu (isiZulu)" },
];

export const normalizeLanguageValue = (value) => {
  if (Array.isArray(value)) {
    return value.map((item) => String(item || '').trim()).filter(Boolean);
  }
  if (typeof value === 'string' && value.trim()) {
    return value.split(',').map((item) => item.trim()).filter(Boolean);
  }
  return [];
};

export const formatLanguageDisplay = (value, fallback = '') => {
  const tokens = normalizeLanguageValue(value);
  if (!tokens.length) return fallback;
  return tokens
    .map((token) => {
      const byId = LANGUAGE_OPTIONS.find((o) => o.id === token);
      if (byId) return byId.name;
      const byName = LANGUAGE_OPTIONS.find(
        (o) => o.name.toLowerCase() === token.toLowerCase()
      );
      return byName ? byName.name : token;
    })
    .join(', ');
};
